name: money_talks_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  cupertino_icons: ^1.0.2
  google_fonts:
  flutter_lints: ^2.0.0
  firebase_core:
  firebase_auth:
  flutter_svg: ^1.0.3
  animated_text_kit: ^4.2.1
  titled_navigation_bar: ^5.0.0-nullsafety.0
  flutter_rating_bar:
  font_awesome_flutter:
  country_picker: ^2.0.15
  im_stepper: ^0.1.3
  image_picker:
  path_provider:
  path:
  cupertino_stepper: ^0.2.1
  simple_animations: ^4.0.1
  cached_network_image: ^3.1.0
  supercharged: ^2.1.1
  chopper: ^4.0.1
  json_annotation: ^4.4.0
  flutter_holo_date_picker: ^1.0.3
  intl: ^0.17.0
  collapsible_sidebar: ^2.0.1+2

dev_dependencies:
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.4
  swagger_dart_code_generator: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
